# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class StripeMock < Formula
  desc "stripe-mock is a mock HTTP server that responds like the real Stripe API. It can be used instead of Stripe's testmode to make test suites integrating with Stripe faster and less brittle."
  homepage "https://github.com/stripe/stripe-mock"
  version "0.129.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stripe/stripe-mock/releases/download/v0.129.0/stripe-mock_0.129.0_darwin_amd64.tar.gz"
      sha256 "dd9314ef4694aafaeb73d93a2e61d82a4259b67f3146bc895a2b90dae1fe08d2"

      def install
        bin.install "stripe-mock"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stripe/stripe-mock/releases/download/v0.129.0/stripe-mock_0.129.0_darwin_arm64.tar.gz"
      sha256 "1c58d333f4ae0291911e6fec7d97468999437e5fd91d04ec1ec7b4f359dd3b8d"

      def install
        bin.install "stripe-mock"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/stripe/stripe-mock/releases/download/v0.129.0/stripe-mock_0.129.0_linux_amd64.tar.gz"
      sha256 "6026c4b33d6fa6123bd7a384168da3bc35e9f6f9b5b2a58cbfd340ae2204fdeb"

      def install
        bin.install "stripe-mock"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stripe/stripe-mock/releases/download/v0.129.0/stripe-mock_0.129.0_linux_arm64.tar.gz"
      sha256 "372475093cf8a8e1a92a65a60b7a06f5c992c19705077cf4556dfa3c32ece4bc"

      def install
        bin.install "stripe-mock"
      end
    end
  end

  plist_options :startup => false

  def plist; <<~EOS
    <?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>KeepAlive</key>
    <dict>
      <key>SuccessfulExit</key>
      <false/>
    </dict>
    <key>Label</key>
    <string>#{plist_name}</string>
    <key>ProgramArguments</key>
    <array>
      <string>#{opt_bin}/stripe-mock</string>
      <string>-http-port</string>
      <string>12111</string>
      <string>-https-port</string>
      <string>12112</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>WorkingDirectory</key>
    <string>#{var}</string>
    <key>StandardErrorPath</key>
    <string>#{var}/log/stripe-mock.log</string>
    <key>StandardOutPath</key>
    <string>#{var}/log/stripe-mock.log</string>
  </dict>
</plist>

  EOS
  end
end
